### ISSUE TITLE
testen van bewegingsensor HC-SR501

### ISSUE THREAD

**Issue by Quinten331** [vives-project-xp/EOMarkers#10]

**Comment by aitorvannevel** [comment]
Sensor getest. Mogelijkheid om de afstand en tijd in te stellen.
Afstand: 0m - 4m
Tijd: 2s - 200s

Je kan de sensor instellen zodat hij constant blijf detecteren zolang er een persoon aanwezig is, of dat hij altijd na de ingestelde tijd uitschakelt.

https://www.mpja.com/download/31227sc.pdf
![afbeelding](https://github.com/vives-project-xp/EOMarkers/assets/41449816/951c17bf-6781-4db1-97fd-297935752da8)
