### ISSUE TITLE
Tekst toevoegen aan Affiche

### ISSUE THREAD

**Issue by Quinten331** [vives-project-xp/EOMarkers#4]

**Comment by declerckcerian** [comment]
Ik heb de template die aangeboden werd, overgenomen en concept uitgewerkt voor onze affiche. Titel, subtitel en korte uitleg van het project staan reeds vermeld, net zoals de vermelding van het team. Enkel over foto's op de affiche moet nog nagedacht worden.

![Image](https://github.com/vives-project-xp/EOMarkers/assets/113900908/3185dd42-8d04-424a-b8da-b7fab1ef88da)

**Comment by pcvives** [comment]
Done... en je moet nog nadenken over de foto's ;)
