### ISSUE TITLE
Prototype bouwen

### ISSUE THREAD

**Issue by Quinten331** [vives-project-xp/EOMarkers#5]

**Comment by aitorvannevel** [comment]
Eerste prototype gemaakt.
We gebruiken een transistor als schakelaar. Zo kunnen we met het signaal van de pir sensor onze ledstrip doen branden.

https://github.com/vives-project-xp/EOMarkers/assets/41449816/e3350e2a-bc32-47cf-bbb6-c784382c6e3d

![IMG_20230925_141643174](https://github.com/vives-project-xp/EOMarkers/assets/41449816/eb9f3318-a827-4968-b13f-ebf3328cc447)
